### ISSUE TITLE
How accurate is the Location

### ISSUE THREAD

**Issue by abrantie1z** [egbakou/App.User.LocationInfo#1]
Good job sir. I had wanted to know whether there is a way to know how accurate the location returned is? Maybe an Accuracy property?

**Comment by egbakou** [comment]
Thanks!!
This NuGet package allows you to get an approximation of a users location by using the IP Address of the device.
It means that the location depends on the IP Address.
check out [https://ipapi.co/](https://ipapi.co/) for more infomation.

**Comment by abrantie1z** [comment]
ok, i see what u doing here, u built ur nuget around some 1 api so dont have much control other than to rerturn what the api returns ? anyways good job. saw your Countries api too, will look at it

**Comment by egbakou** [comment]
Thanks @abrantie1z 
Waiting for your feedback !
